# -*- coding: utf-8 -*-
"""carbon_function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WndvcavFW4eLMdFOJTR5ReK5ZpbUKxcg
"""

import pandas as pd

url = "https://raw.githubusercontent.com/mpHarm88/streetsmart/master/data/vehicles.csv"
df = pd.read_csv(url, low_memory=False)

def get_co2(user_make, user_model, user_year):

  '''

  This function takes in a user's make, model, and year of a car,
  and returns the metric tons of CO2 emmitted.

  Caution, the "user_model" input is not an exact match, so it just
  returns the results from the first item in the list, which may be
  an approximation of the user's actual model.

  '''

  filter_df = df[df['make'] == user_make]
  filter_df = filter_df[filter_df['model'].str.contains(user_model)]
  filter_df = filter_df[filter_df['year']==user_year]

  #Conversion: There are 0.43 metric tons CO2/barrel
  ### I'm using the 0 index because sometimes this returns multiple results
  carbon = filter_df['barrels08'].tolist()[0] * .43

  ## This is not exact but will work for first iteration

  return carbon

#Testing
#get_co2("Tesla", "Model Y Performance AWD", 2020)

#get_co2("Ford", "F150 Pickup 4WD", 2020)

#get_co2("Toyota", "Prius", 2020)

